debug

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -28,22 +28,17 @@ jobs:
         run: |
           poetry install --no-root
 
-      - name: Debug SSH key
-        env:
-          PRIVATE_KEY: ${{ secrets.ID_RSA }}
-        run: |
-          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-keygen -y -f /dev/stdin || echo "Invalid private key"
-
       - name: Configure SSH key
         env:
           PRIVATE_KEY: ${{ secrets.ID_RSA }}
         run: |
           mkdir -p ~/.ssh
-          echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa
+          echo -e "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+          # Проверка валидности ключа
+          ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null || (echo "Invalid private key" && exit 1)
+          # Добавление хоста в known_hosts
           ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
-          cat ~/.ssh/id_rsa
-          readlink -f ~/.ssh/id_rsa
 
       - name: Run tests
         env:
